# fly.toml app configuration file generated for ziglist on 2024-08-01T13:25:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ziglist'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512'
