# fly.toml app configuration file generated for zigpkg on 2024-07-26T11:12:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zigpkg'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = 256
